// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    /** Default is local-only; never use for production (set DATABASE_URL + HEALTHNET_DATABASE_ROLE on the server). */
    url: process.env["DATABASE_URL"] ?? "file:./prisma/local.db",
  },
});
